version: '3.3'
services:
  elasticsearch:
    image: elasticsearch:8.10.4
    container_name: db
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false